---

- hosts: [localhost]
  become: yes
  vars_files:
    - vars/plex_vars.yml
  tasks:
  - name: Download plex
    ansible.builtin.get_url:
      url: https://downloads.plex.tv/plex-media-server-new/{{ plex_version }}/debian/plexmediaserver_{{ plex_version }}_amd64.deb
      dest: /home/nuc/Downloads/plexfiles/
      mode: '0440'
  - name: Stop plex service
    ansible.builtin.service:
      name: plexmediaserver
      state: stopped
  - name: Install new plex version
    command: sh /home/nuc/bash/dpkg_plex.sh
  - name: Start plex service
    ansible.builtin.service:
      name: plexmediaserver
      state: started
